### ISSUE TITLE
testUploadDownloadAnnoBlockCutout unit test FAILS

### ISSUE THREAD

**Issue by wrgr** [neurodata/CAJAL#55]
Critical for science.  Post fails for an unknown reason.  Works on Kunal's development server.  Likely something simple, possibly due to propagate?

===== Test Case Failure =====
Location: /Users/graywr1/code/cajal-docs/test/matlab/api/testOCP.m
Name:     testUploadDownloadAnnoBlockCutout

/Users/graywr1/code/cajal-docs/api/matlab/ocp/OCPNetwork.m at line 342
/Users/graywr1/code/cajal-docs/api/matlab/ocp/OCPNetwork.m at line 300
/Users/graywr1/code/cajal-docs/api/matlab/ocp/OCP.m at line 1932
/Users/graywr1/code/cajal-docs/api/matlab/ocp/OCP.m at line 1232
/Users/graywr1/code/cajal-docs/test/matlab/api/testOCP.m at line 287

Server Response 500 - INTERNAL SERVER ERROR

**Comment by alexbaden** [comment]
Ah hah! 
`raise OCPCAError ("Conflicting data types for overwrite")`
Here is the entire trace:

```
[27/Aug/2015 22:08:12] "POST /ocp/ca/apiUnitTests/apiUnitTestKasthuri/hdf5/1/2560,3760/1000,2200/128,144/overwrite/ HTTP/1.1" 500 734974
[27/Aug/2015 22:08:26] ERROR [ocp:cube:117]Conflicting data types for overwrite
[27/Aug/2015 22:08:26] ERROR [ocp:ocpcarest:713]POST transaction rollback. global name 'OCPCAError' is not defined
Traceback (most recent call last):
  File "/usr/share/ocp/open-connectome/ocpca/ocpcarest.py", line 689, in selectPost
    db.annotateDense ( ch, corner, resolution, voxarray, conflictopt )
  File "/usr/share/ocp/open-connectome/ocpca/ocpcadb.py", line 742, in annotateDense
    cube.overwrite ( databuffer [ z*zcubedim:(z+1)*zcubedim, y*ycubedim:(y+1)*ycubedim, x*xcubedim:(x+1)*xcubedim ] )
  File "/usr/share/ocp/open-connectome/ocpca/cube.py", line 118, in overwrite
    raise OCPCAError ("Conflicting data types for overwrite")
NameError: global name 'OCPCAError' is not defined
[27/Aug/2015 22:08:26] ERROR [ocp:views:95]Unknown exception in getCutout.
Traceback (most recent call last):
  File "/usr/share/ocp/open-connectome/django/ocpca/views.py", line 80, in cutout
    django.http.HttpResponse(ocpcarest.putCutout(webargs,request.body))
  File "/usr/share/ocp/open-connectome/ocpca/ocpcarest.py", line 744, in putCutout
    return selectPost ( rangeargs, proj, db, postdata )
  File "/usr/share/ocp/open-connectome/ocpca/ocpcarest.py", line 689, in selectPost
    db.annotateDense ( ch, corner, resolution, voxarray, conflictopt )
  File "/usr/share/ocp/open-connectome/ocpca/ocpcadb.py", line 742, in annotateDense
    cube.overwrite ( databuffer [ z*zcubedim:(z+1)*zcubedim, y*ycubedim:(y+1)*ycubedim, x*xcubedim:(x+1)*xcubedim ] )
  File "/usr/share/ocp/open-connectome/ocpca/cube.py", line 118, in overwrite
    raise OCPCAError ("Conflicting data types for overwrite")
NameError: global name 'OCPCAError' is not defined
[27/Aug/2015 22:08:26] ERROR [django.request:base:256]Internal Server Error: /ocp/ocp/ca/apiUnitTests/apiUnitTestKasthuri/hdf5/1/2560,3760/1000,2200/128,144/overwrite/
Traceback (most recent call last):
  File "/usr/share/ocp/virtualenvs/ocp/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/share/ocp/open-connectome/django/ocpca/views.py", line 96, in cutout
    raise OCPCAError("Unknown exception in getCutout")
OCPCAError: 'Unknown exception in getCutout'
```

So, you basically have some junk in the dsp029 apiUnitTestKasthuri channel tables. I deleted the and recreated it manually, and now the test passes.

**Comment by alexbaden** [comment]
Not so fast. So, one of the unit tests must be writing garbage data, or dsp029 has some problem accepting that local servers / other servers do not. 

Reopening...

**Comment by wrgr** [comment]
Ok.  I think I tracked this down.  I added Line 277 in testOCP.m:

```
d = uint32(d); %TODO
```

d is of type double with checkerboard.  Apparently this used to get cast in the hdf5 packaging or post to uint32 and all was well, but now is not.  As far as I can tell, this resolves the issue.

@alexbaden - can you merge your probmap fix and make sure this fixes the problem?  Should we add a check on datatype or cast to keep this from being a problem?

Last thing in cajal sell-off critical path for science!

**Comment by alexbaden** [comment]
It does get cast in the hdf5 packaging for uint32 annotations:

```
                                case eRAMONChannelDataType.uint32
                                    switch ramonObj.channelType                                           
                                        case eRAMONChannelType.annotation % TODO this is where the test fails 
                                            % Create HDF5 file
                                            h5Handle =  H5F.create(hdfFile, 'H5F_ACC_TRUNC', 'H5P_DEFAULT', 'H5P_DEFAULT');
                                            % add group 
                                            gid = H5G.create(h5Handle,ramonObj.channel,'H5P_DEFAULT','H5P_DEFAULT','H5P_DEFAULT');
                                            % 32Bit annotations
                                            OCPHdf.addBlockData(h5Handle, ramonObj, uint32(ramonObj.data), 'H5T_STD_U32LE','H5T_NATIVE_INT');

                                        otherwise 
                                            error('OCPHdf:UnsupportedUploadType','Unsupported type for block style uploads');
                                    end
```

So, I think this is a problem in a different function?

**Comment by wrgr** [comment]
well, but casting to uint32 fixes this, right?

The other thing I tried was changing the xoffsets from 2560 to 5560 and
that helped, but I don't think it was necessary.

Best,
Will

**Comment by alexbaden** [comment]
It's cast when you write to HDF5. 

I found one piece of data that wasn't being cast when writing to HDF5. I cast it... let's see how this goes.

**Comment by alexbaden** [comment]
Fixed. https://github.com/openconnectome/CAJAL/commit/214910dc901d6282b92e06c7f5e5cd27a8e1c79a
